### PR TITLE
envPaths specified explicitly

### PR DESCRIPTION
**Pull request by kgofron**
Simplify deployment of multiple devices.

### CODE REVIEW

**Comment by MarkRivers** [comment]
Why can't the envPaths in your iocBoot/iocXXX directory be used?   What is "make" producing for envPaths for your iocBoot/iocXXX directories?

**Comment by kgofron** [comment]
My epics/iocs/TetrAMM-178 has only link to quadEM/iocBoot/iocTetrAMM/st.cmd, and a device "unique.cmd" file (IP, PV PREFIX,...). My iocTetrAMM is here https://github.com/kgofron/TetrAMM. I believe I would have to copy the envPath to each of my 5 AH501, and 2 of my TetrAMMs, 2 of my NSLS_EMs.

**Comment by MarkRivers** [comment]
How does unique.cmd get invoked?

**Comment by kgofron** [comment]
The st.cmd is modified as follows:

#!/epics/support2/quadEM/bin/linux-x86_64/quadEMTestApp

errlogInit(5000)
epicsEnvSet("QUADEM",   "/epics/support2/quadEM")
epicsEnvSet("QUAD_DET", "NSLS_EM.cmd")
epicsEnvSet("IOC",  "iocTetrAMM")
< $(QUADEM)/iocBoot/$(IOC)/envPaths
< unique.cmd

**Comment by MarkRivers** [comment]
I'm confused.  Your https://github.com/kgofron/TetrAMM does not contain an st.cmd you can edit.  The st.cmd there is just a soft link $(QUADEM)/iocBoot/iocTetrAMM/st.cmd.  What st.cmd are you modifying?  Are you modifying this one: $(QUADEM)/iocBoot/iocTetrAMM/st.cmd?

**Comment by kgofron** [comment]
Correct, I am modifying $(QUADEM)/iocBoot/iocTetrAMM/st.cmd

**Comment by MarkRivers** [comment]
Well if you are modifying that st.cmd anyway then I suggest you just make that edit to the location of envPaths while you are editing.  The pull request is to do something non-standard which is prone to errors.  If I change the name of the iocTetrAMM or iocAH501 directory, for example, I need to remember to edit st.cmd.  It is safer to have relative paths there.  Pulling in an st.cmd via a soft link from a directory which does not use the standard EPICS build system is very non-standard, and I don't want to make changes to accommodate it.

**Comment by kgofron** [comment]
No problem, and thanks for considering it.

**Pull request closed without merging**
