### PR TITLE
replace op/ui/*.ui with op/ui/autoconvert/*.ui

### PR DESCRIPTION
**Pull request by nmarks99**
ui files in the top level /op/ui reference nonexistant PVs "Sum12", "Sum32", "Sum1234" etc. which where changed to "SumX", "SumY", and "SumAll" since commit ce37a5e4 and several commits after it on 6/29/2014.

The ui files that were in op/ui/autoconvert correctly reference the "X", "Y", "All" PVs so this commit removes op/ui/*.ui and moves op/ui/autoconvert/*.ui to op/ui/ so caQtDM start scripts in XXX will reference a working ui file.

### CODE REVIEW

**Review by MarkRivers — CHANGES_REQUESTED** [review]
It appears to me that at least in some cases you renamed the files from op/ui/autoconvert to op/ui.  The files in op/ui/autoconvert no longer exist.  For example:
quadEMApp/op/ui/autoconvert/AH501C.ui

**Comment by MarkRivers** [comment]
In fact when I look at your repository the op/ui/autoconvert directory no longer exists at all.  This is not what we want.

**Comment by nmarks99** [comment]
Basically all I did here is the following from the quadEMApp/op/ui directory:
`rm *.ui`
`mv autoconvert/*.ui .`

The intent was to get rid of the out of date .ui files in /op/ui and replace them with the working .ui files in op/ui/autoconvert. Perhaps this isn't what we want and instead we should just do the `rm` command above and not the `mv`, therefore removing the old .ui files and leaving the autoconvert directory as is? (I did this in the most recent commit)

This came to my attention because when clicking the quadEM tab in the xxx default screen, the quadEMApp/op/ui/quadEM.ui is started (which is an out of date ui file) while quadEMApp/op/ui/autoconvert/quadEM.ui is up to date and working.

**Comment by keenanlang** [comment]
> Perhaps this isn't what we want and instead we should just do the rm command above and not the mv, therefore removing the old .ui files and leaving the autoconvert directory as is? 

XXX adds both the autoconvert and the top-level ui directories to the search path. The top-level ui directory comes before the autoconvert so that theoretically new or customized files can be found rather than the automatically converted files, but in this instance the files there are actually the older ones. Removing the old files should be all that is necessary.

**Comment by prjemian** [comment]
Here's the standard plan.  Assume a screen for CSS Studio in BOB format:

1. author/edit the `appApp/op/adl/some_screen.adl` file with MEDM's editor
1. translate `appApp/op/adl/some_screen.adl` to BOB and place in `appApp/op/bob/autoconvert/some_screen.bob`
1. For any custom screens (including rewrites), put that in `appApp/op/bob/some_screen.bob`

- For MEDM, always look in `appApp/op/bob/`.
- For any other display manager, first look in `appApp/op/bob/` and if not found, then look in `appApp/op/bob/autoconvert/`.

**Comment by prjemian** [comment]
When gathering screens to place in an all-in-one directory, first copy from the `autoconvert/` directory, then copy from its parent.  The local overrides will rewrite any screen from `autoconvert/`.

Don't forget that some screens will have additional files (.jpg, .jpeg, .gif, ...).  Those should be copied as well.

revised for typos

**Comment by prjemian** [comment]
We consider MEDM as the master format.  Translators from `.adl` to other exist for all the popular display managers.  Other translators might exist but are not well-known.  Usually, translation is limited by the application with the least widgets.

**Comment by nmarks99** [comment]
Thanks all for the clarification - my latest commit should be good then as it just removes the outdated files in op/ui.

**Pull request merged**
